### PR TITLE
recommit all files and ignored unwanted files

### PR DESCRIPTION
**Pull request by ghost**
Ignored the unwanted files correctly 😀

### CODE REVIEW

**Comment by BIntelligent** [comment]
why did you delete db.json it will give error when someone uses it as i don't have auto file create

**Comment by BIntelligent** [comment]
imma make so it makes file if it dosnt exist.

**Comment by itstyonirwansyah** [comment]
i thought you were ignoring it

**Comment by ghost** [comment]
your were ignoring it before i was creating this pull request

**Comment by ghost** [comment]
test

**Comment by itstyonirwansyah** [comment]
test

**Comment by ghost** [comment]
testpng


> Why did you delete db.json it will give error when someone uses it as i don't have auto file create

Don't worry, a `writeFileSync` method automatically creates a file when it does not exist.

**Comment by ghost** [comment]
@BIntelligent

**Comment by BIntelligent** [comment]
ok i believe you.

**Comment by BIntelligent** [comment]
but what about url property inside?

**Comment by BIntelligent** [comment]
wait nvm

**Comment by BIntelligent** [comment]
change package.json version.

**Comment by ghost** [comment]
Thanks for merging my pull request 😁

**Pull request merged**
