### PR TITLE
Update typing

### PR DESCRIPTION
**Pull request by GillHoang**
https://github.com/BIntelligent/currency-system/issues/23

Just wait me to complete this

### CODE REVIEW

**Comment by GillHoang** [comment]
maybe done

**Comment by GillHoang** [comment]
i miss something, i will add it when i free

**Comment by BIntelligent** [comment]
Oki, please proof check if everything works because I am kinda busy and won't be able to review everything

**Comment by BIntelligent** [comment]
And TYSM, for adding TypeScript, This'll help alot of people.

**Comment by GillHoang** [comment]
> And TYSM, for adding TypeScript, This'll help alot of people.

np

**Comment by GillHoang** [comment]
> Oki, please proof check if everything works because I am kinda busy and won't be able to review everything

in weekend, i will complete it and fix some types

**Comment by GillHoang** [comment]
image

this is demo

**Comment by BIntelligent** [comment]
Weren't we suppose to merge it?

**Pull request closed without merging**
